<?php

namespace PHPSP\Bundles\SouphpspBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends EntityRepository
{
    
    public function findActiveChallenges()
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->andWhere('c.startDate <= CURRENT_TIMESTAMP()');
        $qb->andWhere('c.endDate >= CURRENT_TIMESTAMP()');
        
        return $qb->getQuery()->getResult();
    }
    
    public function findRecentChallenges()
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->andWhere('c.endDate <= CURRENT_TIMESTAMP()');
        $qb->andWhere('c.endDate > ?0');
        
        $qb->setParameter(0, new \DateTime('-1 month'));
        
        return $qb->getQuery()->getResult();
    }
    
}