<?php

namespace PHPSP\Bundles\SouphpspBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionRepository extends EntityRepository
{
    
    public function findMyContributions($uid)
    {
        
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.userId = ?0');
        
        $qb->setParameter(0, $uid);
        
        $qb->orderBy('c.dateApproved', 'DESC');
        $qb->orderBy('c.dateAdded', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * @todo make function return entity in aliased field, not 0
     * @return type 
     */
    public function getTopContributors($limit = 10)
    {
    
        $qb = $this->createQueryBuilder('c');
        
        $qb->addSelect('COUNT(DISTINCT c.id) as contribs');
        $qb->addGroupBy('c.userId');

        $qb->orderBy('contribs', 'DESC');
        
        $qb->setMaxResults($limit);
        
        return $qb->getQuery()->getResult();
    }
}