<?php

namespace PHPSP\Bundles\SouphpspBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrizeRepository extends EntityRepository
{
}