<?php

namespace PHPSP\Bundles\SouphpspBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    
    public function getActiveProjects()
    {
        $qb = $this->createQueryBuilder('p');
        
        $qb->andWhere('p.status = ?0');
        $qb->orderBy('p.name');
        
        $qb->setParameter(0, Project::STATUS_OK);
        
        return $qb->getQuery()->getResult();
    }
    
    
}