parameters:
    database_driver:   "pdo_mysql"
    database_host:     "localhost"
    database_port:     ""
    database_name:     "souphpsp"
    database_user:     "root"
    database_password: "root"

    mailer_transport: "gmail"
    mailer_user:      "bot@phpsp.org.br"
    mailer_password:  "php5p80t"

    locale:           "en"

    secret:           "4aba5ba9e6c6e5468e16d9c97668b9d440cd5a64"
    site:
        url:         "http://souphpsp.local"

    cache:
        host:       "localhost"
        port:       11211 

    admin:
        emails:     "rdohms@phpsp.org.br"