security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    providers:
         fos_twitter:
             id: phpsp.twitter.auth

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured:
            pattern:    ^/
            anonymous: ~
            fos_twitter: true
            logout: ~
            provider: fos_twitter

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/souphpsp$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/souphpsp/u/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/souphpsp/about/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/souphpsp/admin/, roles: ROLE_ADMIN  }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        
