services:
    phpsp.cache:
        class: PHPSP\Bundles\WebBundle\Services\Cache\Service
        arguments: 
            config: 
                adapterClass: Doctrine\Common\Cache\MemcacheCache
                prefix: phpsp_cache_
                options:
                    servers: [{host: %cache.host%, port: %cache.port%}]
                                        
    phpsp.chart:
        class: PHPSP\Bundles\WebBundle\Services\Graph\Service
                    
    phpsp.twitter.api:
        class: PHPSP\Bundles\WebBundle\Services\Twitter\Api
        arguments: 
            twitter: @fos_twitter.api
            cache:   @phpsp.cache
            
    phpsp.twitter.auth:
        class: PHPSP\Bundles\WebBundle\Services\Twitter\Security\TwitterProvider
        arguments:
            twitter: @fos_twitter.service
            container: @service_container
                
    phpsp.twitter.twig.extension:
        class: PHPSP\Bundles\WebBundle\Services\Twitter\Twig\Extension
        arguments:
            twitter: @phpsp.twitter.api
        tags:
            - { name: twig.extension }
            
    phpsp.localedate.twig.extension:
        class: PHPSP\Twig\Extension\LocaleDate
        tags:
            - { name: twig.extension }
