services:
    souphpsp.chart.builder:
        class: PHPSP\Bundles\SouphpspBundle\Services\Chart\Builder
        arguments:
            doctrine: @doctrine
            graph: @phpsp.chart
    souphpsp.twig.challengeExtension:
        class: PHPSP\Bundles\SouphpspBundle\Twig\Extension\ChallengeInfo
        arguments:
            doctrine: @doctrine
        tags:
            - { name: twig.extension }